server:
  port: 8090  # Puerto específico para el perfil dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-app-market
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never  # Ejecuta `schema.sql` y `data.sql`